/* NIVEL 1 · CAMINO A CASA. No necesita imágenes ni audios para funcionar. */
(() => {
  'use strict';
  const $ = id => document.getElementById(id);
  const W = 12, H = 8, CROSS_X = 5;
  const state = {x:1,y:1,dir:1,lives:3,mistakes:0,atCrossing:false,waited:false,crossed:false,paused:false,finished:false,phase:0,remaining:7,sound:false,carX:[0,11],lastMove:0};
  const directions = [{dx:0,dy:-1,label:'↑ Norte',rotation:0},{dx:1,dy:0,label:'→ Este',rotation:90},{dx:0,dy:1,label:'↓ Sur',rotation:180},{dx:-1,dy:0,label:'← Oeste',rotation:270}];
  const playerFrames = ['atras.png','derecha.png','adelante.png','izquierda.png'];
  const assets = {school:'escuela.png',home:'casa.png',tree:'arbol.png',light:'semaforo.png'};
  const emojis = {school:'🏫',home:'🏡',tree:'🌳',light:'🚦',flowers:'🌼',bush:'🌿'};
  const decor = {'1,0':'school','10,7':'home','0,0':'tree','3,0':'tree','7,0':'tree','11,0':'tree','0,7':'tree','3,7':'flowers','7,7':'tree','11,7':'tree','4,2':'light','6,5':'light','9,1':'bush','2,6':'flowers'};
  const map = $('map');
  function tileType(x,y){if(y===3||y===4)return x===CROSS_X?'crosswalk':'road';if(y===1||y===2||y===5||y===6)return 'sidewalk';if(x===1&&y===0)return 'school';if(x===10&&y===7)return 'home';return 'grass';}
  function makeMap(){map.replaceChildren();for(let y=0;y<H;y++)for(let x=0;x<W;x++){const tile=document.createElement('div');const type=tileType(x,y);tile.className=`tile ${type}`;tile.dataset.x=x;tile.dataset.y=y;const thing=decor[`${x},${y}`];if(thing){const img=document.createElement('img');img.src=`assets/images/${assets[thing]||thing+'.png'}`;img.alt='';img.onerror=()=>{img.hidden=true};const fallback=document.createElement('span');fallback.className='fallback';fallback.textContent=emojis[thing]||'🌼';tile.append(img,fallback);}if(x===10&&y===6){tile.textContent='🏠';tile.classList.add('home');}map.append(tile);}map.append($('player'),$('car-one'),$('car-two'));}
  function locate(el,x,y){el.style.left=`${x/W*100}%`;el.style.top=`${y/H*100}%`;}
  function draw(){locate($('player'),state.x,state.y);const playerImage=$('player').querySelector('img');const frame=`assets/images/${playerFrames[state.dir]}`;if(playerImage.getAttribute('src')!==frame){playerImage.src=frame;playerImage.hidden=false;}/* Cambiar imagen solo al girar; al avanzar conserva el mismo frame. */$('direction').textContent=directions[state.dir].label;$('hearts').textContent='❤️'.repeat(state.lives)+'🤍'.repeat(3-state.lives);$('stars').textContent='★'.repeat(Math.max(1,3-Math.min(2,state.mistakes)))+'☆'.repeat(Math.min(2,state.mistakes));$('task-crosswalk').classList.toggle('done',state.atCrossing);$('task-crosswalk').textContent=(state.atCrossing?'✓ ':'○ ')+'Encuentra el paso peatonal';$('task-wait').classList.toggle('done',state.waited);$('task-wait').textContent=(state.waited?'✓ ':'○ ')+'Espera el verde peatonal y verifica los autos';$('task-home').classList.toggle('done',state.finished);$('task-home').textContent=(state.finished?'✓ ':'○ ')+'Llega a casa';$('position').textContent=state.y<=2?'📍 Cerca de la escuela':state.y<=4?'📍 Cruzando la avenida':'📍 Cerca de casa';$('map-status').textContent=state.crossed?'¡Ahora llega a casa!':state.atCrossing?'Observa el semáforo':'Busca las franjas blancas';}
  function sfx(name){if(!state.sound)return;const el=$(name+'-sfx');if(el){el.currentTime=0;el.play().catch(()=>{});}}
  function feedback(message,kind=''){const el=$('feedback');el.textContent=message;el.className='feedback '+kind;}
  function phase(){return ['green','yellow','red'][state.phase];}
  function signal(){const p=phase();['red','yellow','green'].forEach(c=>$('car-'+c).classList.toggle('on',p===c));$('ped-stop').classList.toggle('on',p!=='red');$('ped-go').classList.toggle('on',p==='red');$('car-label').textContent=p==='red'?'DETENIDOS':p==='yellow'?'PRECAUCIÓN':'EN MARCHA';$('ped-label').textContent=p==='red'?'PUEDES CRUZAR*':'ESPERA';$('countdown').textContent=state.remaining+' s';$('safety').textContent=p==='red'?'*Mira a ambos lados y comprueba que los autos estén detenidos.':'Espera en la acera; no entres en la calzada.';}
  function stopped(){return phase()==='red' && state.carX[0]<=3 && state.carX[1]>=8;}
  function moveCars(){if(state.paused||state.finished)return;if(phase()==='red'){state.carX=[Math.min(state.carX[0],2),Math.max(state.carX[1],9)];}else{state.carX[0]+=0.25;state.carX[1]-=0.25;if(state.carX[0]>12.5)state.carX[0]=-1.5;if(state.carX[1]<-1.5)state.carX[1]=12.5;}locate($('car-one'),state.carX[0],3);locate($('car-two'),state.carX[1],4);}
  function tick(){if(state.paused||state.finished)return;/* Si el niño ya está en el cruce, mantenemos el rojo vehicular. */if(state.y===3||state.y===4){state.phase=2;state.remaining=Math.max(4,state.remaining);}else{state.remaining--;if(state.remaining<=0){state.phase=(state.phase+1)%3;state.remaining=[7,2,8][state.phase];if(state.phase===2){state.carX=[2,9];}}}signal();}
  function error(message,penalty=false){feedback(message,'bad');sfx('wrong');if(penalty){state.lives--;state.mistakes++;if(state.lives<=0){state.finished=true;$('lose-overlay').hidden=false;}}draw();}
  function turn(delta){if(state.paused||state.finished)return;state.dir=(state.dir+delta+4)%4;sfx('click');draw();}
  function step(){if(state.paused||state.finished)return;if(Date.now()-state.lastMove<145)return;state.lastMove=Date.now();const d=directions[state.dir],nx=state.x+d.dx,ny=state.y+d.dy;if(nx<0||nx>=W||ny<0||ny>=H){error('¡Ese camino termina aquí! Busca otra dirección.');return;}const type=tileType(nx,ny);if(type==='grass'||type==='school'||type==='home'){error('Camina por la acera, no por los jardines.');return;}if(type==='road'){error('¡Peligro! No cruces fuera del paso peatonal.',true);return;}if(type==='crosswalk'){
      if(state.y===2&&ny===3){state.atCrossing=true;if(!stopped()){error('¡Espera! Necesitas verde peatonal y autos completamente detenidos.',true);return;}state.waited=true;feedback('¡Bien! Los autos están detenidos. Cruza por las franjas blancas.','good');sfx('correct');}
      else if(state.y===5&&ny===4){error('Tu casa está al sur. Usa el cruce cuando necesites regresar.');return;}
      else if(state.y===3||state.y===4){if(nx!==CROSS_X){error('Mantente dentro de las franjas blancas.');return;}}
      else{error('Acércate al paso peatonal desde la acera.');return;}
    }
    if((state.y===3||state.y===4)&&nx!==CROSS_X){error('Termina de cruzar en línea recta.');return;}
    state.x=nx;state.y=ny;if(ny===5&&state.waited&&!state.crossed){state.crossed=true;feedback('¡Excelente! Cruzaste de forma segura. Ahora ve a casa.','good');sfx('correct');}
    if(nx===CROSS_X&&ny===2){state.atCrossing=true;feedback('¡Encontraste el cruce! Espera el verde peatonal y mira los autos.','good');}
    if(nx===10&&ny===6&&state.crossed){win();return;}sfx('step');draw();}
  function win(){state.finished=true;draw();const stars=Math.max(1,3-Math.min(2,state.mistakes));$('final-stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('win-text').textContent=stars===3?'¡Fantástico! Esperaste el momento seguro y llegaste sin errores.':'¡Llegaste! Recuerda esperar el verde peatonal y comprobar que los autos se detengan.';if(window.SemaforoProgreso){window.SemaforoProgreso.save(1,stars);}sfx('win');$('win-overlay').hidden=false;}
  function reset(){Object.assign(state,{x:1,y:1,dir:1,lives:3,mistakes:0,atCrossing:false,waited:false,crossed:false,paused:false,finished:false,phase:0,remaining:7,carX:[0,11],lastMove:0});['pause-overlay','win-overlay','lose-overlay'].forEach(id=>$(id).hidden=true);feedback('¡Camina por la acera hasta el paso peatonal!');draw();signal();moveCars();}
  function pause(toggle){if(state.finished)return;state.paused=toggle;$('pause-overlay').hidden=!toggle;}
  function sound(toggle){state.sound=toggle;$('sound').textContent=toggle?'🔊':'🔇';$('sound').setAttribute('aria-label',toggle?'Silenciar':'Activar sonido');window.SemaforoProgreso?.setSound(toggle);const music=$('music');music.volume=.25;if(toggle)music.play().catch(()=>{});else music.pause();}
  function orientation(){ $('rotate').hidden=!(matchMedia('(orientation: portrait)').matches&&innerWidth<750); }
  $('left').addEventListener('click',()=>turn(-1));$('right').addEventListener('click',()=>turn(1));$('forward').addEventListener('click',step);$('pause').addEventListener('click',()=>pause(true));$('resume').addEventListener('click',()=>pause(false));$('restart-pause').addEventListener('click',reset);$('again').addEventListener('click',reset);$('retry').addEventListener('click',reset);$('sound').addEventListener('click',()=>sound(!state.sound));
  document.addEventListener('keydown',e=>{if(['ArrowUp','ArrowLeft','ArrowRight',' ','w','a','d','W','A','D'].includes(e.key))e.preventDefault();if(state.paused||state.finished)return;if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')turn(-1);else if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')turn(1);else if(e.key==='ArrowUp'||e.key===' '||e.key.toLowerCase()==='w')step();});
  makeMap();reset();sound(window.SemaforoProgreso?.soundEnabled()||false);orientation();addEventListener('resize',orientation);setInterval(tick,1000);setInterval(moveCars,350);
})();
