/* Sonidos sintetizados con Web Audio: no requiere archivos ni conexión. */
(()=>{'use strict';const type=document.body.dataset.robot;const $=id=>document.getElementById(id);const buttons=[...document.querySelectorAll('[data-seconds]')];const timer=$('timer'),fill=$('progress'),stage=$('stage'),status=$('status'),sub=$('substatus'),start=$('start'),stop=$('stop'),custom=$('custom');let mode='random',selected=0,ctx=null,active=false,interval=null,timeout=null,scheduled=[],endAt=0,duration=0,beat=0;
function audio(){if(!ctx)ctx=new (window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(freq,length,kind='sine',volume=.075,delay=0,sweep=0){if(!ctx)return;const t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=kind;o.frequency.setValueAtTime(freq,t);if(sweep)o.frequency.exponentialRampToValueAtTime(Math.max(1,sweep),t+length);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(volume,t+.012);g.gain.exponentialRampToValueAtTime(.0001,t+length);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+length+.025);scheduled.push(o);o.onended=()=>{scheduled=scheduled.filter(x=>x!==o);o.disconnect();g.disconnect()}}
function pulse(){if(type==='beebot'){tone(180,.19,'sawtooth',.028,0,220);tone(225,.18,'triangle',.055,.03,175)}else if(type==='rayet'){tone(690,.085,'square',.037);tone(840,.08,'sine',.055,.13);if(beat%3===2)tone(480,.13,'triangle',.045,.27)}else{tone(430,.14,'sine',.07,0,680);tone(760,.13,'triangle',.055,.17,500)}beat++}
function finishSound(){if(type==='beebot'){tone(195,.9,'sawtooth',.042,0,330);tone(275,1.05,'triangle',.075,.13,480);tone(540,.45,'sine',.07,1.04)}else if(type==='rayet'){tone(870,1.55,'square',.055);tone(880,1.55,'sine',.065)}else{[523,659,784,1047].forEach((f,i)=>tone(f,.32,'sine',.095,i*.22));tone(1047,.8,'triangle',.075,.9)}}
function display(sec){timer.textContent=Math.ceil(Math.max(0,sec)).toString().padStart(2,'0')+' s'}function choose(m,s){if(active)return;mode=m;selected=s||0;buttons.forEach(b=>b.classList.toggle('selected',b.dataset.seconds===String(s)&&m==='preset'||b.dataset.seconds==='random'&&m==='random'));display(m==='random'?20:selected);fill.style.width='0%';status.textContent='¡Prepara al robot!';sub.textContent=m==='random'?'El tiempo será una sorpresa':`Duración: ${selected} segundos`}
function clear(){if(interval)clearInterval(interval);if(timeout)clearTimeout(timeout);interval=timeout=null;scheduled.forEach(o=>{try{o.stop()}catch(e){}});scheduled=[]}
function complete(){if(!active)return;active=false;clearInterval(interval);interval=null;display(0);fill.style.width='100%';stage.classList.remove('active');stage.classList.add('done');status.textContent='¡El robot ha elegido!';sub.textContent='¡Pasa el turno al niño que tiene el robot!';start.disabled=false;start.textContent='↻ Volver a jugar';stop.disabled=true;finishSound()}
function begin(){if(active)return;try{audio()}catch(e){status.textContent='No se pudo activar el sonido';return}clear();stage.classList.remove('done');duration=mode==='random'?10+Math.floor(Math.random()*11):selected;if(!duration)return;active=true;beat=0;endAt=performance.now()+duration*1000;start.disabled=true;stop.disabled=false;stage.classList.add('active');status.textContent='¡El robot está buscando!';sub.textContent='Pásalo de mano en mano…';display(duration);fill.style.width='0%';pulse();interval=setInterval(()=>{let remaining=Math.max(0,(endAt-performance.now())/1000);display(remaining);fill.style.width=`${Math.min(100,(1-remaining/duration)*100)}%`;if(remaining<=0){complete();return}const elapsed=duration-remaining;if(Math.floor(elapsed*2)>Math.floor((elapsed-.12)*2))pulse()},120);timeout=setTimeout(complete,duration*1000)}
function cancel(){if(!active)return;active=false;clear();stage.classList.remove('active');status.textContent='Temporizador detenido';sub.textContent='Puedes elegir otro tiempo';start.disabled=false;start.textContent='▶ Iniciar';stop.disabled=true;fill.style.width='0%';display(mode==='random'?20:selected)}
buttons.forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.seconds;choose(v==='random'?'random':'preset',v==='random'?0:Number(v))}));custom.addEventListener('change',()=>{const n=Number(custom.value);if(!Number.isInteger(n)||n<1||n>300){custom.setCustomValidity('Elige entre 1 y 300 segundos');custom.reportValidity();return}custom.setCustomValidity('');choose('custom',n)});custom.addEventListener('input',()=>custom.setCustomValidity(''));start.addEventListener('click',begin);stop.addEventListener('click',cancel);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&active&&performance.now()>=endAt)complete()});choose('random',0);
})();
