(()=>{'use strict';
const ABC=[...'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ'],VOC=[...'AEIOU'];
const ST=window.TREN_NIVELES;
const $=s=>document.querySelector(s),app=$('#app'),rand=n=>Math.floor(Math.random()*n),shuffle=a=>[...a].sort(()=>Math.random()-.5),fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;
const key='tren-abc-estaciones-v2';let saved;try{saved=JSON.parse(localStorage.getItem(key))||{}}catch{saved={}};saved.records??={};saved.stars??={};saved.settings??={music:true,sfx:true,hints:true,difficulty:'suave'};saved.train??='coral';let station=0,round=0,task=null,filled={},chosen=null,selectedSlot=null,lives=3,score=0,hits=0,misses=0,elapsed=0,clock=null,start=0,paused=false,screen='menu',busy=false,undo=[],audioCtx;
function persist(){try{localStorage.setItem(key,JSON.stringify(saved))}catch{}}
function beep(type){if(!saved.settings.sfx)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const notes=type==='ok'?[520,690]:type==='bad'?[260,210]:type==='win'?[523,659,784,1046]:[480];notes.forEach((f,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.11;o.frequency.value=f;o.type='sine';g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(.045,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(g).connect(audioCtx.destination);o.start(t);o.stop(t+.19)})}catch{}}
const button=(txt,act,cls='primary')=>`<button class="btn ${cls}" data-act="${act}">${txt}</button>`;
function scenery(scene){const s=ST.find(x=>x.scene===scene)||ST[0];return `<div class="scenery ${scene}" aria-hidden="true"><div class="sun"></div><div class="cloud cloud1"></div><div class="cloud cloud2"></div><div class="mountain m1"></div><div class="mountain m2"></div><div class="hill h1"></div><div class="hill h2"></div><div class="decor">${s.decor}</div></div>`}
function render(html,name){screen=name;app.innerHTML=html;bind()}
function menu(){clearInterval(clock);render(`<div class="page menu">${scenery('spring')}<div class="menu-panel"><span class="eyebrow">🌈 ¡UNA AVENTURA SOBRE RIELES!</span><h1>EL TREN DEL <span>ABECEDARIO</span></h1><p>¡Cada estación es una aventura diferente!</p><div class="hero-loco">🚂 <span>🚃 🚃 🚃</span></div><div class="menu-actions">${button('🚂 ¡VAMOS A JUGAR!','map')}${button('🎨 Mi locomotora','garage','secondary')}${button('⚙️ Configuración','settings','outline')}</div><small>🗺️ 6 estaciones abiertas · ⭐ ${Object.values(saved.stars).reduce((a,b)=>a+b,0)} estrellas</small></div></div>`,'menu')}
function map(){clearInterval(clock);render(`<div class="page map">${scenery('spring')}<header class="page-head"><button data-act="menu" class="round-btn">←</button><h1>🗺️ ¡Elige tu estación!</h1><span class="tag">Todas disponibles ✨</span></header><div class="map-grid">${ST.map((s,i)=>`<button class="map-card ${s.scene}" data-act="start" data-id="${i}"><span class="map-icon">${s.icon}</span><small>ESTACIÓN ${i+1}</small><strong>${s.name}</strong><span>${s.desc}</span><b>${'⭐'.repeat(saved.stars[i]||0)}${'☆'.repeat(3-(saved.stars[i]||0))}</b><em>${saved.records[i]?`⏱️ Mejor: ${fmt(saved.records[i].time)}`:'¡Lista para jugar!'}</em></button>`).join('')}</div></div>`,'map')}
function garage(){render(`<div class="page garage">${scenery('autumn')}<div class="modal-panel"><h1>🎨 Elige tu locomotora</h1><div class="garage-grid">${[['coral','❤️ Coral'],['ocean','💙 Océano'],['mint','💚 Menta'],['golden','💛 Dorado']].map(([id,n])=>`<button class="garage-item ${saved.train===id?'active':''}" data-act="train" data-id="${id}"><span class="big-emoji">🚂</span>${n}</button>`).join('')}</div>${button('← Volver','menu','secondary')}</div></div>`,'garage')}
function settings(){render(`<div class="page settings">${scenery('summer')}<div class="modal-panel"><h1>⚙️ Configuración</h1><label><input type="checkbox" data-setting="sfx" ${saved.settings.sfx?'checked':''}> 🔊 Efectos de sonido</label><label><input type="checkbox" data-setting="hints" ${saved.settings.hints?'checked':''}> 💡 Mostrar pistas</label><label>🎯 Dificultad <select data-setting="difficulty">${[['suave','Suave · Sin perder vidas'],['normal','Normal · 4 vidas'],['reto','Reto · 3 vidas']].map(([v,t])=>`<option value="${v}" ${saved.settings.difficulty===v?'selected':''}>${t}</option>`).join('')}</select></label>${button('Guardar y volver','menu')}</div></div>`,'settings')}
function makeTask(){let mode=ST[station].mode;if(mode==='mixed')mode=['fill','order','lower','pair','fill','order'][round%6];const pool=station===0?VOC:ABC;let len=station===0?3:station===1?5:mode==='pair'?3:mode==='order'?4:5;let begin=rand(pool.length-len+1),seq=pool.slice(begin,begin+len);if(mode==='pair'){seq=shuffle(ABC).slice(0,3);return {mode,seq,missing:[0,1,2],options:shuffle(seq.map(c=>c.toLowerCase()).concat(shuffle(ABC.filter(c=>!seq.includes(c))).slice(0,2).map(c=>c.toLowerCase()))),title:'¡Cada letra tiene su pareja!',help:'Arrastra cada minúscula debajo de su mayúscula.'}}
if(mode==='lower'){return {mode,seq,missing:seq.map((_,i)=>i),options:shuffle(seq.map(c=>c.toLowerCase()).concat(shuffle(ABC.filter(c=>!seq.includes(c))).slice(0,2).map(c=>c.toLowerCase()))),title:'¡La montaña de las minúsculas!',help:'Cada vagón muestra una mayúscula. Encuentra su minúscula.'}}
if(mode==='order')return {mode,seq,missing:seq.map((_,i)=>i),options:shuffle(seq),title:'¡Ordena los vagones!',help:'Coloca las letras en orden alfabético, de izquierda a derecha.'};let n=station===0?1:station===1?2:3,missing=shuffle(seq.map((_,i)=>i)).slice(0,n).sort((a,b)=>a-b);let options=missing.map(i=>seq[i]);let extras=shuffle(pool.filter(x=>!options.includes(x))).slice(0,Math.min(3,pool.length-options.length));return {mode,seq,missing,options:shuffle([...options,...extras]),title:station===0?'¡Rescata las vocales!':'¡Completa el tren!',help:'Arrastra las letras a los vagones vacíos.'}}
function startLevel(i){station=i;round=0;lives=saved.settings.difficulty==='reto'?3:4;score=0;hits=0;misses=0;elapsed=0;paused=false;start=Date.now();clearInterval(clock);clock=setInterval(()=>{if(screen==='game'&&!paused){elapsed=Math.floor((Date.now()-start)/1000);let el=$('#clock');if(el)el.textContent=fmt(elapsed)}},300);newRound()}
function newRound(){task=makeTask();filled={};chosen=null;selectedSlot=null;busy=false;undo=[];game()}
function needed(i){return task.missing.includes(i)}function answer(i){return task.mode==='pair'||task.mode==='lower'?task.seq[i].toLowerCase():task.seq[i]}
function wagons(){return task.seq.map((c,i)=>{let fixed=!needed(i),value=filled[i]??(fixed?c:'');let above=task.mode==='pair'||task.mode==='lower'?`<span class="wagon-top">${c}</span>`:'';return `<div class="wagon-wrap"><div class="wagon ${value?'has-letter':''} ${selectedSlot===i?'target':''} ${fixed?'fixed':''}" data-slot="${i}" tabindex="0" role="button" aria-label="Vagón ${i+1}: ${value||'vacío'}">${above}<span class="wagon-letter">${value||'?'}</span><span class="wagon-shine"></span></div><div class="coupler"></div><div class="wheel-set"><i></i><i></i></div></div>`}).join('')}
function game(){let s=ST[station],percent=Math.round((round/ST[station].rounds)*100);render(`<div class="page gameplay ${s.scene}">${scenery(s.scene)}<header class="hud"><button class="round-btn" data-act="pause" title="Pausar">Ⅱ</button><div class="hud-level">${s.icon} <span><small>ESTACIÓN ${station+1}</small><strong>${s.name}</strong></span></div><div class="hud-progress">🚉 <strong>${round+1}/${s.rounds}</strong><div class="mini-bar"><i style="width:${percent}%"></i></div></div><div class="hud-stats"><span>❤️ <b>${saved.settings.difficulty==='suave'?'∞':lives}</b></span><span>⭐ <b id="score">${score}</b></span><span>⏱️ <b id="clock">${fmt(elapsed)}</b></span></div></header><section class="game-instruction"><span class="bear">🐻</span><div><h2>${task.title}</h2><p>${task.help}</p></div><span class="instruction-badge">${percent}%</span></section><section class="world"><div class="world-label">${task.mode==='pair'?'🌈 ¡Encuentra cada pareja!':task.mode==='lower'?'🏔️ De MAYÚSCULA a minúscula':task.mode==='order'?'🏘️ ¡Ordena de izquierda a derecha!':'🚂 ¡El tren te necesita!'}</div><div class="train-scroller"><div class="train"><div class="engine ${saved.train}"><div class="engine-smoke">☁️</div><div class="engine-top"></div><div class="engine-cabin">🚂</div><div class="engine-wheel"><i></i><i></i><i></i></div></div>${wagons()}</div></div><div class="rail"><div></div></div></section><section class="dock"><div class="dock-heading"><div><h3>🔠 ${task.mode==='pair'?'ENCUENTRA LAS PAREJAS':task.mode==='lower'?'ELIGE LAS MINÚSCULAS':task.mode==='order'?'ORDENA LAS LETRAS':'ARRASTRA LAS LETRAS'}</h3><small>${chosen!==null?'Ahora toca un vagón vacío.':'Arrastra una letra o tócala para colocarla.'}</small></div><div class="dock-tools">${button('↶ Deshacer','undo','soft')}${button('⌫ Borrar','clear','soft danger')}</div></div><div class="letter-options">${task.options.map((c,i)=>`<button class="tile ${chosen===i?'picked':''} ${Object.values(filled).filter(v=>v===c).length>=task.options.filter(v=>v===c).length?'used':''}" data-letter="${i}" draggable="true" aria-label="Letra ${c}">${c}</button>`).join('')}</div><div class="dock-tip" id="tip">💡 ${saved.settings.hints?'Puedes arrastrar o tocar una letra. Si te equivocas, ¡vuelve a intentarlo!':'¡Tú puedes!'}</div></section></div>`,'game');dragSetup()}
function place(i,li){if(busy||!needed(i)||filled[i]!==undefined)return;let c=task.options[li];if(c===undefined)return;let used=Object.values(filled).filter(x=>x===c).length,available=task.options.filter(x=>x===c).length;if(used>=available)return;if(c===answer(i)){undo.push({...filled});filled[i]=c;chosen=null;selectedSlot=null;hits++;score+=100;beep('ok');game();const w=$(`[data-slot="${i}"]`);w?.classList.add('pop');if(task.missing.every(k=>filled[k]!==undefined)){busy=true;setTimeout(advance,900)}}else{misses++;beep('bad');let tip=$('#tip');if(tip)tip.textContent=saved.settings.hints?`💡 Busca la letra ${answer(i)} para este vagón. ¡Inténtalo otra vez!`:'¡Prueba con otra letra!';$(`[data-slot="${i}"]`)?.classList.add('shake');if(saved.settings.difficulty!=='suave'){lives--;let h=$('.hud-stats');if(h)h.querySelector('span b').textContent=lives;if(lives<=0){busy=true;setTimeout(()=>finish(false),800)}}}}
function pick(i){if(busy)return;if(task.options[i]===undefined)return;chosen=i;if(selectedSlot!==null){place(selectedSlot,i);return}let next=task.missing.find(k=>filled[k]===undefined&&answer(k)===task.options[i]);if(next!==undefined)place(next,i);else{let target=task.missing.find(k=>filled[k]===undefined);if(target!==undefined)place(target,i)}}
function slot(i){if(busy||!needed(i))return;if(filled[i]!==undefined){undo.push({...filled});delete filled[i];chosen=null;game();return}if(chosen!==null)place(i,chosen);else{selectedSlot=i;game()}}
function advance(){round++;if(round>=ST[station].rounds)finish(true);else{let t=$('.train');t?.classList.add('depart');setTimeout(newRound,650)}}
function finish(win){clearInterval(clock);elapsed=Math.floor((Date.now()-start)/1000);let accuracy=Math.round(hits/Math.max(1,hits+misses)*100),stars=win?(misses===0?3:misses<=3?2:1):0;if(win){let old=saved.records[station];if(!old||elapsed<old.time)saved.records[station]={time:elapsed,score,accuracy};saved.stars[station]=Math.max(stars,saved.stars[station]||0);persist();beep('win')}render(`<div class="page results">${scenery(ST[station].scene)}<div class="result-panel"><div class="result-icon">${win?'🏆':'💛'}</div><h1>${win?'¡Llegaste a la estación!':'¡Buen intento, maquinista!'}</h1><p>${win?'¡Has completado un viaje fantástico!':'¡Cada intento te ayuda a aprender! Puedes intentarlo de nuevo.'}</p><div class="result-stars">${win?'⭐'.repeat(stars)+'☆'.repeat(3-stars):'🌟 ¡Tú puedes!'}</div><div class="result-stats"><div><strong>${fmt(elapsed)}</strong><small>⏱️ Tiempo</small></div><div><strong>${hits}</strong><small>✅ Aciertos</small></div><div><strong>${misses}</strong><small>🔄 Errores</small></div><div><strong>${accuracy}%</strong><small>🎯 Precisión</small></div><div><strong>${score}</strong><small>⭐ Puntos</small></div><div><strong>${saved.records[station]?fmt(saved.records[station].time):'--:--'}</strong><small>🏅 Mejor tiempo</small></div></div><p class="advice">${win?'🎉 ¡Felicitaciones! Puedes elegir cualquier estación en el mapa.':'💡 Consejo: observa las letras del tren y busca cuál viene antes o después.'}</p><div class="result-actions">${button('🔁 Reintentar','retry','secondary')}${button('🗺️ Elegir estación','map')}${win&&station<5?button('🚂 Siguiente estación','next','outline'):''}</div></div></div>`,'results')}
function pause(){if(screen!=='game')return;paused=true;elapsed=Math.floor((Date.now()-start)/1000);render(`<div class="page pause">${scenery(ST[station].scene)}<div class="modal-panel"><h1>⏸️ ¡Una pequeña pausa!</h1><p>Tu tren te está esperando. ⏱️ ${fmt(elapsed)}</p>${button('▶ Continuar','resume')}${button('🔁 Reiniciar','retry','secondary')}${button('🗺️ Volver al mapa','map','outline')}</div></div>`,'pause')}
function dragSetup(){document.querySelectorAll('[data-letter]').forEach(el=>{el.addEventListener('dragstart',e=>{e.dataTransfer.setData('text/plain',el.dataset.letter);e.dataTransfer.effectAllowed='move'});el.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse')return;el.dataset.px=e.clientX;el.dataset.py=e.clientY});el.addEventListener('pointerup',e=>{if(e.pointerType==='mouse'||el.dataset.px===undefined)return;let dx=e.clientX-Number(el.dataset.px),dy=e.clientY-Number(el.dataset.py);delete el.dataset.px;delete el.dataset.py;if(Math.hypot(dx,dy)<24)return;let target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(target){e.preventDefault();e.stopPropagation();place(Number(target.dataset.slot),Number(el.dataset.letter))}})});document.querySelectorAll('[data-slot]').forEach(el=>{el.addEventListener('dragover',e=>{e.preventDefault();el.classList.add('drag-over')});el.addEventListener('dragleave',()=>el.classList.remove('drag-over'));el.addEventListener('drop',e=>{e.preventDefault();el.classList.remove('drag-over');place(Number(el.dataset.slot),Number(e.dataTransfer.getData('text/plain')))})})}
function bind(){app.querySelectorAll('[data-act]').forEach(el=>el.addEventListener('click',()=>{let a=el.dataset.act;beep('click');if(a==='menu')menu();else if(a==='map')map();else if(a==='garage')garage();else if(a==='settings')settings();else if(a==='start')startLevel(+el.dataset.id);else if(a==='train'){saved.train=el.dataset.id;persist();garage()}else if(a==='pause')pause();else if(a==='resume'){paused=false;start=Date.now()-elapsed*1000;game()}else if(a==='retry')startLevel(station);else if(a==='next')startLevel(Math.min(station+1,5));else if(a==='undo'){if(undo.length){filled=undo.pop();chosen=null;selectedSlot=null;game()}}else if(a==='clear'){if(Object.keys(filled).length){undo.push({...filled});filled={};chosen=null;selectedSlot=null;game()}}}));app.querySelectorAll('[data-letter]').forEach(el=>el.addEventListener('click',()=>pick(+el.dataset.letter)));app.querySelectorAll('[data-slot]').forEach(el=>{el.addEventListener('click',()=>slot(+el.dataset.slot));el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();slot(+el.dataset.slot)}})});app.querySelectorAll('[data-setting]').forEach(el=>el.addEventListener('change',()=>{saved.settings[el.dataset.setting]=el.type==='checkbox'?el.checked:el.value;persist()}))}
menu();})();
