(()=>{'use strict';
const type=document.body.dataset.robot,$=id=>document.getElementById(id),buttons=[...document.querySelectorAll('[data-seconds]')];
const timer=$('timer'),fill=$('progress'),stage=$('stage'),status=$('status'),sub=$('substatus'),start=$('start'),stop=$('stop'),pause=$('pause'),custom=$('custom'),banner=$('finish-banner'),silence=$('silence');
let mode='random',selected=0,ctx=null,state='idle',tickId=null,beatId=null,celebrateId=null,nodes=new Set(),duration=20,remaining=20,endAt=0,beats=0,celebrations=0;
function audio(){ctx??=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function tone(f,d,w='sine',vol=.06,delay=0,to=0){if(!ctx)return;let t=ctx.currentTime+delay,o=ctx.createOscillator(),g=ctx.createGain();o.type=w;o.frequency.setValueAtTime(f,t);if(to)o.frequency.exponentialRampToValueAtTime(Math.max(1,to),t+d);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.015);g.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(g).connect(ctx.destination);nodes.add(o);o.onended=()=>{nodes.delete(o);o.disconnect();g.disconnect()};o.start(t);o.stop(t+d+.03)}
function quiet(){clearInterval(beatId);clearInterval(celebrateId);beatId=celebrateId=null;nodes.forEach(o=>{try{o.stop()}catch{}});nodes.clear()}
function pulse(){if(type==='beebot'){tone(185,.21,'sawtooth',.024,0,260);tone(245,.23,'triangle',.055,.045,170)}else if(type==='rayet'){tone(740,.085,'square',.035);tone(990,.095,'sine',.048,.16);if(beats%3===2)tone(510,.12,'triangle',.04,.32)}else{tone(370,.16,'sine',.06,0,710);tone(780,.15,'triangle',.05,.2,480);if(beats%4===3)tone(1020,.17,'sine',.04,.37)}beats++}
function finale(){if(type==='beebot'){tone(220,.3,'sawtooth',.026,0,390);tone(350,.38,'triangle',.065,.18,530);tone(660,.36,'sine',.07,.57)}else if(type==='rayet'){tone(850,.65,'square',.043);tone(870,.65,'sine',.052);tone(1040,.2,'triangle',.035,.72)}else{[523,659,784,1047].forEach((f,i)=>tone(f,.22,'sine',.068,i*.17));tone(1318,.32,'triangle',.06,.72)}}
function display(sec){timer.textContent=String(Math.ceil(Math.max(0,sec))).padStart(2,'0')+' s'}
function choose(m,s=0){if(state==='running'||state==='paused')return;quiet();banner.hidden=true;stage.classList.remove('done');mode=m;selected=s;remaining=duration=m==='random'?20:s;buttons.forEach(b=>b.classList.toggle('selected',m==='random'?b.dataset.seconds==='random':m==='preset'&&Number(b.dataset.seconds)===s));display(duration);fill.style.width='0%';status.textContent='¡Prepara al robot!';sub.textContent=m==='random'?'El tiempo será una sorpresa':`Duración: ${s} segundos`;start.textContent='▶ Iniciar '+(type==='beebot'?'zumbido':type==='rayet'?'radar':'misión')}
function render(){display(remaining);fill.style.width=Math.max(0,Math.min(100,100*(1-remaining/duration)))+'%'}
function finish(){if(state!=='running')return;clearInterval(tickId);tickId=null;quiet();state='finished';remaining=0;render();stage.classList.remove('active');stage.classList.add('done');status.textContent='¡El robot ha elegido!';sub.textContent='¡El niño que tiene el robot ha sido elegido!';start.disabled=false;start.textContent='↻ Volver a jugar';pause.disabled=true;stop.disabled=true;banner.hidden=false;celebrations=0;function play(){if(celebrations>=7){clearInterval(celebrateId);celebrateId=null;return}finale();celebrations++;banner.querySelector('span:nth-of-type(2)').textContent=`Celebración ${celebrations} de 7 · Puedes silenciarla.`}play();celebrateId=setInterval(play,type==='rayet'?1250:1450)}
function update(){if(state!=='running')return;remaining=Math.max(0,(endAt-performance.now())/1000);render();if(remaining<=0)finish()}
function begin(){if(state==='running')return;try{audio()}catch{status.textContent='Activa el sonido de tu navegador';return}quiet();clearInterval(tickId);banner.hidden=true;stage.classList.remove('done');duration=mode==='random'?10+Math.floor(Math.random()*11):selected;if(!duration)return;remaining=duration;endAt=performance.now()+duration*1000;state='running';beats=0;start.disabled=true;pause.disabled=false;pause.textContent='Ⅱ Pausar';stop.disabled=false;stage.classList.add('active');status.textContent='¡El robot está buscando!';sub.textContent='Pásalo de mano en mano…';render();pulse();beatId=setInterval(pulse,type==='beebot'?530:type==='rayet'?610:700);tickId=setInterval(update,70)}
function pauseResume(){if(state==='running'){update();if(state!=='running')return;state='paused';clearInterval(tickId);quiet();stage.classList.remove('active');status.textContent='¡En pausa!';sub.textContent='Pulsa Reanudar cuando estés listo';pause.textContent='▶ Reanudar'}else if(state==='paused'){audio();state='running';endAt=performance.now()+remaining*1000;stage.classList.add('active');status.textContent='¡El robot está buscando!';sub.textContent='Pásalo de mano en mano…';pause.textContent='Ⅱ Pausar';pulse();beatId=setInterval(pulse,type==='beebot'?530:type==='rayet'?610:700);tickId=setInterval(update,70)}}
function cancel(){if(state!=='running'&&state!=='paused')return;clearInterval(tickId);quiet();state='idle';stage.classList.remove('active');status.textContent='Temporizador detenido';sub.textContent='Elige un tiempo para volver a jugar';start.disabled=false;pause.disabled=true;pause.textContent='Ⅱ Pausar';stop.disabled=true;remaining=duration=mode==='random'?20:selected;render()}
buttons.forEach(b=>b.addEventListener('click',()=>{let v=b.dataset.seconds;choose(v==='random'?'random':'preset',v==='random'?0:Number(v))}));custom.addEventListener('change',()=>{let n=Number(custom.value);if(!Number.isInteger(n)||n<1||n>300){custom.setCustomValidity('Elige entre 1 y 300 segundos');custom.reportValidity();return}custom.setCustomValidity('');choose('custom',n)});custom.addEventListener('input',()=>custom.setCustomValidity(''));start.addEventListener('click',begin);pause.addEventListener('click',pauseResume);stop.addEventListener('click',cancel);silence.addEventListener('click',()=>{quiet();banner.querySelector('span:nth-of-type(2)').textContent='Sonido detenido. ¡Puedes volver a jugar!';silence.disabled=true;setTimeout(()=>silence.disabled=false,400)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state==='running')update()});choose('random');
})();