(()=>{'use strict';
const ROBOT='ludio';const $=id=>document.getElementById(id);const choices=[...document.querySelectorAll('.choice')];const display=$('timeDisplay'),fill=$('progressFill'),message=$('message'),badge=$('statusBadge');let selected='random',duration=0,remaining=0,deadline=0,phase='idle',timer=null,audio=null,master=null,compressor=null,muted=false,activeSounds=new Set(),audioEvents=[],celebrationCount=0,celebrationNext=0,pausedCelebrationDelay=0,beepStep=0;
const themes={beebot:{emoji:['🌸','🌼','🌺','🦋','🌷'],idle:'¡La abeja está lista para volar!',run:'¡Bzz, bzz! Pasa la abejita',end:'🌸 ¡Bee-Bot eligió a alguien! 🌸'},rugged:{emoji:['⚡','✦','◈','✧','💠'],idle:'¡Radar preparado!',run:'¡Pi, pi, pi! El radar está buscando',end:'⚡ ¡Objetivo encontrado! ⚡'},ludio:{emoji:['✨','💜','⭐','✦','🪐'],idle:'¡Portal preparado!',run:'¡Ludio está explorando!',end:'✨ ¡Misión cumplida! ✨'}};
const cfg=themes[ROBOT];const particles=$('particles');for(let i=0;i<30;i++){const s=document.createElement('span');s.className='particle';s.textContent=cfg.emoji[i%cfg.emoji.length];s.style.setProperty('--x',((i*37+13)%100)+'%');s.style.setProperty('--size',(13+(i*7)%16)+'px');s.style.setProperty('--dur',(7+i%9)+'s');s.style.setProperty('--delay',(-i*.8)+'s');particles.append(s)}
function ensureAudio(){if(audio)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;audio=new AC();master=audio.createGain();compressor=audio.createDynamicsCompressor();compressor.threshold.value=-18;compressor.knee.value=18;compressor.ratio.value=8;compressor.attack.value=.004;compressor.release.value=.17;master.gain.value=muted?0:.88;master.connect(compressor);compressor.connect(audio.destination)}
function tone(freq,dur=.13,type='sine',volume=.45,offset=0,endFreq){if(!audio||muted)return;const t=audio.currentTime+offset,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(endFreq)o.frequency.exponentialRampToValueAtTime(endFreq,t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(Math.max(.001,volume),t+.012);g.gain.setValueAtTime(Math.max(.001,volume),t+Math.max(.015,dur-.045));g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(master);o.start(t);o.stop(t+dur+.02);activeSounds.add(o);o.onended=()=>{activeSounds.delete(o);try{o.disconnect();g.disconnect()}catch(e){}}}
function silence(){for(const o of activeSounds){try{o.stop()}catch(e){}}activeSounds.clear()}
function tickSound(){if(ROBOT==='beebot'){tone(190,.18,'sawtooth',.12,0,260);tone(245,.13,'triangle',.22,.06,195)}else if(ROBOT==='rugged'){tone([750,930,780,550][beepStep++%4],.115,'square',.23)}else{tone([410,610,790,510][beepStep++%4],.18,'triangle',.42,0,270)}}
function finale(){if(ROBOT==='beebot'){tone(350,.25,'triangle',.55);tone(510,.25,'triangle',.5,.25);tone(680,.42,'sine',.62,.5);tone(850,.42,'sine',.3,.53)}else if(ROBOT==='rugged'){tone(740,.15,'square',.33);tone(920,.15,'square',.35,.2);tone(1180,.48,'sawtooth',.35,.42)}else{[440,554,659,880].forEach((n,i)=>tone(n,.26,'triangle',.55,i*.19));tone(1108,.44,'sine',.5,.8)}}
function setBadge(t){badge.textContent=t}function setButtons(){const running=phase==='running',paused=phase==='paused',celebrating=phase==='celebrating';$('start').disabled=running||celebrating;$('pause').disabled=!(running||paused||celebrating||phase==='pausedFinal');$('pause').textContent=(paused||phase==='pausedFinal')?'▶ Reanudar':celebrating?'⏸ Pausar sonido':'⏸ Pausar';$('stop').disabled=phase==='idle';choices.forEach(x=>x.disabled=phase!=='idle');$('customSeconds').disabled=phase!=='idle';document.body.classList.toggle('running',running);document.body.classList.toggle('celebrate',celebrating)}
function updateClock(){display.textContent=selected==='random'&&phase==='running'?'?':Math.ceil(remaining);fill.style.width=duration?Math.max(0,Math.min(100,100*(duration-remaining)/duration))+'%':'0%'}
function reset(){clearInterval(timer);timer=null;silence();phase='idle';remaining=selected==='random'?0:Number(selected);duration=0;celebrationCount=0;display.textContent=selected==='random'?'?':remaining;fill.style.width='0%';message.textContent=cfg.idle;setBadge('● LISTO PARA JUGAR');setButtons()}
function finish(){clearInterval(timer);timer=null;silence();remaining=0;display.textContent='🎉';fill.style.width='100%';phase='celebrating';celebrationCount=0;message.textContent=cfg.end;setBadge('★ ¡ENCONTRADO!');setButtons();playFinale()}
function playFinale(){if(phase!=='celebrating')return;if(celebrationCount>=7){phase='finished';setBadge('★ ¡MISIÓN CUMPLIDA!');message.textContent=cfg.end+' Pulsa iniciar para jugar otra vez.';setButtons();return}finale();celebrationCount++;celebrationNext=performance.now()+ (ROBOT==='ludio'?1850:ROBOT==='beebot'?1650:1400);timer=setTimeout(playFinale,celebrationNext-performance.now())}
function runClock(){clearInterval(timer);phase='running';deadline=performance.now()+remaining*1000;let lastBeep=-1;message.textContent=cfg.run;setBadge('● BUSCANDO...');setButtons();timer=setInterval(()=>{remaining=Math.max(0,(deadline-performance.now())/1000);const elapsed=Math.floor((duration-remaining));if(elapsed!==lastBeep){lastBeep=elapsed;tickSound()}updateClock();if(remaining<=0)finish()},80)}
choices.forEach(btn=>btn.addEventListener('click',()=>{if(phase!=='idle')return;selected=btn.dataset.seconds;choices.forEach(x=>x.classList.toggle('active',x===btn));$('customSeconds').value='';remaining=selected==='random'?0:Number(selected);display.textContent=selected==='random'?'?':remaining;message.textContent=selected==='random'?'El tiempo será una sorpresa entre 10 y 20 segundos':`¡Listo! ${remaining} segundos`;}));
$('customSeconds').addEventListener('input',()=>{if(phase!=='idle')return;const val=Number($('customSeconds').value);if($('customSeconds').value!==''&&Number.isInteger(val)&&val>=1&&val<=300){selected=String(val);choices.forEach(x=>x.classList.remove('active'));remaining=val;display.textContent=val;message.textContent=`¡Listo! ${val} segundos`}else if($('customSeconds').value!==''){message.textContent='Introduce un número entero de 1 a 300 segundos'}});
$('start').addEventListener('click',async()=>{if(phase==='running'||phase==='celebrating')return;if(phase==='finished')reset();const custom=$('customSeconds').value;if(custom!==''&&(!Number.isInteger(Number(custom))||Number(custom)<1||Number(custom)>300)){message.textContent='Introduce un tiempo entre 1 y 300 segundos';return}ensureAudio();try{if(audio&&audio.state==='suspended')await audio.resume()}catch(e){}duration=selected==='random'?10+Math.floor(Math.random()*11):Number(selected);remaining=duration;beepStep=0;runClock()});
$('pause').addEventListener('click',()=>{if(phase==='running'){remaining=Math.max(0,(deadline-performance.now())/1000);clearInterval(timer);timer=null;silence();phase='paused';message.textContent='⏸ Temporizador en pausa';setBadge('Ⅱ EN PAUSA');setButtons();updateClock()}else if(phase==='celebrating'){clearTimeout(timer);timer=null;silence();pausedCelebrationDelay=Math.max(0,celebrationNext-performance.now());phase='pausedFinal';message.textContent='⏸ Señal final en pausa';setBadge('Ⅱ EN PAUSA');$('pause').textContent='▶ Reanudar';$('pause').disabled=false;$('stop').disabled=false;document.body.classList.remove('celebrate')}else if(phase==='paused'){runClock()}else if(phase==='pausedFinal'){phase='celebrating';message.textContent=cfg.end;setButtons();timer=setTimeout(playFinale,pausedCelebrationDelay)}});
$('stop').addEventListener('click',reset);$('soundToggle').addEventListener('click',()=>{muted=!muted;if(master)master.gain.value=muted?0:.88;if(muted)silence();$('soundToggle').textContent=muted?'🔇 Silenciado':'🔊 Sonido';$('soundToggle').setAttribute('aria-pressed',String(muted))});document.addEventListener('visibilitychange',()=>{if(document.hidden&&phase==='running')$('pause').click()});reset();
})();